image: node

before_script:
    - yarn

cache:
    paths:
        - node_modules/

pages:
    stage: deploy
    script:
        - yarn build
        - cp -r _public/. public/
    artifacts:
        paths:
            - public
    only:
        - gitlabe_pages
